aanguage: generic
dist: xenial
git:
  depth: 10

jobs:
  include:
    - name: Vim 8.0
      os: linux
      env:
        - VIM_VERSION=v8.0.0000
        - THEMIS_PROFILE=vim-profile-v8.0.txt
    - name: Vim 8.1
      os: linux
      env:
        - VIM_VERSION=v8.1.0005
        - THEMIS_PROFILE=vim-profile-v8.1.txt
    - name: Vim master
      os: linux
      env:
        - VIM_VERSION=master
        - THEMIS_PROFILE=vim-profile-master.txt
    - name: Vim MacVim latest
      os: osx
      osx_image: xcode9.4
      env:
        - THEMIS_PROFILE=vim-profile-osx.txt
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew/
          - /usr/local/Homebrew/Library/Homebrew/vendor/
          - /usr/local/Homebrew/Library/Taps/
      before_cache:
        - brew cleanup
    - name: Vim Lint only
      os: linux
      env:
        - RUN_LINT=true

addons:
  apt:
    packages:
      - language-pack-ja
      - vim
      - python-dev
      - python3-dev
      - python3-pip
  homebrew:
    packages:
      - macvim
    update: true

install:
  - rvm reset
  - bash scripts/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH
    # Install https://github.com/Vimjas/covimerage
  - pip3 install --user --upgrade pip
  - pip3 install --user --upgrade setuptools
  - pip3 install --user covimerage

before_script:
  - git clone --depth 1 --branch v1.5.4 --single-branch https://github.com/thinca/vim-themis /tmp/vim-themis
  - git clone --depth 1 --single-branch https://github.com/vim-jp/vital.vim /tmp/vital.vim
  - git clone --depth 1 https://github.com/Shougo/vimproc.vim /tmp/vimproc
  - (cd /tmp/vimproc && make)

script:
  - uname -a
  - which -a vim
  - vim --version
  - |
    if [[ "${RUN_LINT}" != "true" ]]; then
        /tmp/vim-themis/bin/themis --runtimepath /tmp/vimproc --runtimepath /tmp/vital.vim --exclude ConcurrentProcess --reporter dot
    fi
  - if [[ "${RUN_LINT}" == "true" ]] ; then bash scripts/run-lint-on-ci.sh ; fi

after_success:
  - bash scripts/coverage.sh
